;;; SPDX-License-Identifier: GPL-3.0-or-later
;;; Run the unmodified, vendored undo-tree in real Emacs, producing JSON traces.
(require 'json)
(require 'cl-lib)
(require 'undo-tree)
(setq undo-tree-auto-save-history nil)
(defun port-trace-node (node names)
  (let ((name (gethash node names)))
    `((name . ,name)
      (parent . ,(gethash (undo-tree-node-previous node) names))
      (children . ,(vconcat (mapcar (lambda (n) (gethash n names)) (undo-tree-node-next node))))
      (branch . ,(or (undo-tree-node-branch node) 0))
      (widths . ,(vector (undo-tree-node-lwidth node) (undo-tree-node-cwidth node) (undo-tree-node-rwidth node))))))
(defun port-trace (tree names)
  (undo-tree-clear-visualizer-data tree)
  (undo-tree-compute-widths (undo-tree-root tree))
  (let (nodes)
    (undo-tree-mapc (lambda (n) (push (port-trace-node n names) nodes)) (undo-tree-root tree))
    `((text . ,(buffer-string))
      (root . ,(gethash (undo-tree-root tree) names))
      (current . ,(gethash (undo-tree-current tree) names))
      (nodes . ,(vconcat (sort nodes (lambda (a b) (string< (alist-get 'name a) (alist-get 'name b)))))))))
(defun port-scenario (scenario)
  (with-temp-buffer
    (buffer-enable-undo)
    (insert (alist-get 'initial scenario))
    (setq buffer-undo-list nil)
    (undo-tree-mode 1)
    (undo-list-transfer-to-tree)
    (let ((names (make-hash-table :test 'eq)) (labels (make-hash-table :test 'equal)) traces)
      (puthash (undo-tree-root buffer-undo-tree) "root" names)
      (puthash "root" (undo-tree-root buffer-undo-tree) labels)
      (push (port-trace buffer-undo-tree names) traces)
      (dolist (op (alist-get 'ops scenario))
        (pcase (alist-get 'type op)
          ("edit"
           (undo-boundary)
           (erase-buffer)
           (insert (alist-get 'text op))
           (undo-boundary)
           (undo-list-transfer-to-tree)
           (let ((node (undo-tree-current buffer-undo-tree)) (label (alist-get 'name op)))
             (puthash node label names) (puthash label node labels)))
          ("undo" (undo-tree-undo))
          ("redo" (undo-tree-redo))
          ("switch" (undo-tree-switch-branch (alist-get 'branch op)))
          ("set" (undo-tree-set (gethash (alist-get 'name op) labels)))
          ("discard" (undo-tree-discard-node (gethash (alist-get 'name op) labels))))
        (push (port-trace buffer-undo-tree names) traces))
      `((name . ,(alist-get 'name scenario)) (traces . ,(vconcat (nreverse traces)))))))
(let* ((json-object-type 'alist) (json-array-type 'list) (json-key-type 'symbol)
       (scenarios (json-read-file (pop command-line-args-left)))
       (clock 1000))
  ;; Deterministic, ordered timestamps exercise source pruning without wall-clock races.
  (cl-letf (((symbol-function 'current-time) (lambda () (seconds-to-time (cl-incf clock)))))
    (princ (json-encode (vconcat (mapcar #'port-scenario scenarios))))))
