;;; SPDX-License-Identifier: GPL-3.0-or-later
;;; Compare the literal buffer produced by unmodified undo-tree's drawing functions.
(require 'json)
(require 'cl-lib)
(require 'subr-x)
(require 'undo-tree)
(defun text-port-scenario (scenario)
  (with-temp-buffer
    (let* ((tree (make-undo-tree)) (nodes (make-hash-table :test 'eql))
           (raw-nodes (alist-get 'nodes scenario))
           (undo-tree-visualizer-lazy-drawing nil)
           (undo-tree-visualizer-timestamps (alist-get 'timestamps scenario))
           (undo-tree-visualizer-relative-timestamps (alist-get 'relativeTimestamps scenario))
           (undo-tree-visualizer-spacing (undo-tree-visualizer-calculate-spacing))
           (undo-tree-visualizer-parent-mtime nil)
           registers)
      (dolist (raw raw-nodes)
        (let ((node (undo-tree-make-node nil nil)))
          (setf (undo-tree-node-timestamp node) (seconds-to-time (/ (alist-get 'time raw) 1000.0)))
          ;; Real Emacs modification-time entries, consumed by node-unmodified-p.
          (when (alist-get 'saved raw) (setf (undo-tree-node-redo node) (list (cons t '(1234 0)))))
          (puthash (alist-get 'id raw) node nodes)))
      (dolist (raw raw-nodes)
        (let* ((node (gethash (alist-get 'id raw) nodes)) (register (alist-get 'register raw)))
          (setf (undo-tree-node-next node) (mapcar (lambda (id) (gethash id nodes)) (alist-get 'children raw))
                (undo-tree-node-branch node) (alist-get 'branch raw))
          (dolist (child (undo-tree-node-next node)) (setf (undo-tree-node-previous child) node))
          (when register
            (let ((key (string-to-char register)))
              (setf (undo-tree-node-register node) key)
              (set-register key (registerv-make (undo-tree-make-register-data (current-buffer) node)))
              (push key registers)))))
      (setf (undo-tree-root tree) (gethash (alist-get 'root scenario) nodes)
            (undo-tree-current tree) (gethash (alist-get 'current scenario) nodes))
      (setq-local buffer-undo-tree tree)
      (cl-letf (((symbol-function 'current-time) (lambda () (seconds-to-time (/ (alist-get 'now scenario) 1000.0)))))
        (undo-tree-draw-tree tree))
      (let ((lines (mapcar #'string-trim-right (split-string (buffer-string) "\n")))
            (top 0) margin positions)
        (while (and lines (string-empty-p (car lines))) (setq lines (cdr lines)) (cl-incf top))
        (while (and lines (string-empty-p (car (last lines)))) (setq lines (butlast lines)))
        (setq margin (apply #'min (delq nil (mapcar (lambda (line) (string-match "[^ ]" line)) lines))))
        (dolist (raw raw-nodes)
          (let ((node (gethash (alist-get 'id raw) nodes)))
            (goto-char (undo-tree-node-marker node))
            (push `((id . ,(alist-get 'id raw)) (row . ,(- (line-number-at-pos) 1 top)) (column . ,(- (current-column) margin))) positions)))
        (dolist (key registers) (set-register key nil))
        `((name . ,(alist-get 'name scenario))
          (text . ,(mapconcat (lambda (line) (substring line (min margin (length line)))) lines "\n"))
          (positions . ,(vconcat (sort positions (lambda (a b) (< (alist-get 'id a) (alist-get 'id b)))))))))))
(let* ((json-object-type 'alist) (json-array-type 'list) (json-key-type 'symbol) (json-false nil) (json-null nil)
       (scenarios (json-read-file (pop command-line-args-left))))
  (princ (json-encode (vconcat (mapcar #'text-port-scenario scenarios)))))
